server.port=8080
spring.application.name=gateway-server

# Eureka Discovery Settings 
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Service Locator settings
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# --- Routes Configuration ---

# Vehicle Service
spring.cloud.gateway.routes[0].id=vehicle-service
spring.cloud.gateway.routes[0].uri=lb://vehicle-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/vehicles/**

# Customer Service
spring.cloud.gateway.routes[1].id=customer-service
spring.cloud.gateway.routes[1].uri=lb://customer-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/customers/**

# Booking Service
spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=lb://booking-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/bookings/**

# --- Global CORS Configuration ---
spring.cloud.gateway.globalcors.add-to-auto-perception=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=https://godrive-frontend-six.vercel.app, https://godrive-frontend-git-main-vinilvidushankas-projects.vercel.app, http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600
