server.port=8080

# Eureka Discovery settings
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Service Locator settings
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Vehicle Service Route
spring.cloud.gateway.routes[0].id=vehicle-service
spring.cloud.gateway.routes[0].uri=lb://VEHICLE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/vehicles/**

# Customer Service Route
spring.cloud.gateway.routes[1].id=customer-service
spring.cloud.gateway.routes[1].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/customers/**

# Booking Service Route
spring.cloud.gateway.routes[2].id=booking-service
spring.cloud.gateway.routes[2].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/bookings/**

spring.cloud.gateway.filter.remove-non-proxy-headers.headers[0]=content-type

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

eureka.client.serviceUrl.defaultZone=http://10.160.0.2:8761/eureka/

spring.application.name=gateway-server
